### PR TITLE
ACM-6854 Upgrade client-go to v0.27.4

### PR DESCRIPTION
**Pull request by lennysgarage**
* [x] I have taken backward compatibility into consideration.

This changes the function signature used for the NonCachingClient, no changes should be made to the actual behaviour of the non-caching client.

Addresses:
 - https://issues.redhat.com/browse/ACM-6854

### CODE REVIEW

**Comment by lennysgarage** [comment]
Having some issues upgrading the client-go version due to the module IBM/controller-filtered-cache . Looks like we'll either need to make a PR to upgrade it's modules or remove it here since it doesn't look like its needed anymore? It's only being used in a single controller, the gitopscluster controller and that controller is already using the non-caching client so the filtered cache shouldn't be filtering into anything, since we're not caching.

**Comment by xiangjingli** [comment]
@lennysgarage  Yeah. I agree that the filtered cache should not be used any more as we have applied the non cache client.

**Pull request merged**
