### PR TITLE
Utilize search collector enhancements to build appset report

### PR DESCRIPTION
**Pull request by philipwu08**
Issue: https://issues.redhat.com/browse/ACM-6165

Description: 
 - Make single call to search instead of 2 separate calls (one to get the applications and another to get the related resources for each application). Use new _parentUid from search to find the related resources for each application.
 - Use the new _missingResources property to include resources that are missing from the related resources

* [ x ] I have taken backward compatibility into consideration.

Signed-off-by: philipwu08 <phwu@redhat.com>

### CODE REVIEW

**Comment by philipwu08** [comment]
/hold 

Need to wait for search PRs to merge first.

**Comment by xiangjingli** [comment]
The PR looks good. We will unhold it once the search enhancements are done

**Pull request merged**
