### PR TITLE
Enhance Application status message

### PR DESCRIPTION
**Pull request by mikeshng**

### CODE REVIEW

**Comment by mikeshng** [comment]
@rhamini3 please take a look as discussed. Thanks.

**Comment by xiangjingli** [comment]
@mikeshng  @rhamini3 maybe we also provide the CLI  so that end users can easily get the argocd app ?  The whole message will be sth like

```
kubectl get multiclusterapplicationsetreports -n <appset NS> <appset Name>
Additional details available in ManagedCluster <cluster name>
kubectl get applications -n <app NS> <app Name>
```
```

**Comment by mikeshng** [comment]
> @mikeshng @rhamini3 maybe we also provide the CLI so that end users can easily get the argocd app ? The whole message will be sth like
> 
> ```
> kubectl get multiclusterapplicationsetreports -n <appset NS> <appset Name>
> Additional details available in ManagedCluster <cluster name>
> kubectl get applications -n <app NS> <app Name>
> ```

Done as suggested. Please take a look again.

**Comment by rhamini3** [comment]
@mikeshng /lgtm, thanks!

**Pull request merged**
